config/routes.rb
Rails.application.routes.draw do
  filter :locale

  inline_route_for :tickets

  resources :customers do
    resources :tickets, shallow: true
  end

  root to: 'customers#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :tickets, dependent: :destroy

	validates :name, presence: true

	def tickets_balance
		self.tickets.inject(0) { |sum, t| sum + t.balance }
  end

  accepts_nested_attributes_for :tickets, allow_destroy: true
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  extend Enumerize

	belongs_to :customer

  after_initialize :set_defaults

	validates :description, presence: true
  validates :quantity, numericality: { greater_than: 0 }, presence: true
  validates :op_type, presence: true

  enumerize :op_type, in: {use: 1, buy: 2}

	default_scope -> { order(:ticket_date) }

  def buy
    self.op_type.buy?
  end

  def balance
    self.quantity * (self.buy ? 1 : -1)
  end

  private
  def set_defaults
    self.ticket_date ||= Date.today
    self.quantity ||= 0
    self.op_type ||= :use
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_locale

  private
  def set_locale
    I18n.locale = params[:locale] || http_accept_language.compatible_language_from(I18n.available_locales.reverse)
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    unless params[:q].blank?
      @q = params[:q]
      @customers = Customer.where("LOWER(name) like LOWER('%#{@q}%')")
      session[:q] = request.original_fullpath
    else
      @customers = Customer.all
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to edit_customer_path(@customer), notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, tickets_attributes: [:description, :ticket_date, :quantity, :op_type, :id, :_destroy])
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  include Inliner

  before_action :set_customer, only: [:index, :new, :create]
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  inline_object :ticket, :customer

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = @customer ? @customer.tickets : Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = @customer ? @customer.tickets.build : Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = @customer.tickets.create(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to edit_customer_path(@customer), notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to customer_tickets_url(@ticket.customer), notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_customer
      @customer = Customer.find(params[:customer_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id]) if params[:id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:description, :ticket_date, :quantity, :customer_id, :quantity_abs, :op_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def tt(value)
    t(value).titleize
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/customers/_form.html.erb
<%= simple_form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :name, as: :string, maxlength: 255 %>
  </div>

    <p><b>Saldo tickets: <%= @customer.tickets_balance %></b></p>

          <%= f.inline_fields_for(:tickets, headers: {description: 'col-xs-7', ticket_date: 'col-xs-2', quantity: 'col-xs-1', operation: 'col-xs-1', _actions: 'col-xs-1'}, add_link_name:'+ Ticket') %>

      <p></p>
    <%= f.submit %>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<p id="notice"><%= notice %></p>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1><%= tt('.title') %></h1>

<%= form_tag(customers_path, method: :get) do %>
    <%= search_field_tag :q, @q %>
<% end %>

<table>
  <thead>
    <tr>
      <th><%= tt('activerecord.attributes.customer.name') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= link_to tt('activerecord.attributes.customer.tickets'), customer_tickets_path(customer) %></td>
        <td><%= link_to tt('edit'), edit_customer_path(customer) %></td>
        <td><%= link_to tt('destroy'), customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to tt('.new'), new_customer_path %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to tt('back'), customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>
<p>
  <strong>Balance:</strong>
  <%= @customer.tickets_balance %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', session[:q] || customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Techticket</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= "#{controller_path} #{action_name}" %>">

<%= yield %>

<%= render 'inline_fields/inline_fields_modal' %>

</body>
</html>

app/views/tickets/_form.html.erb
<%= render 'ticket_fields', f: f %>

<div class="actions">
  <%= f.submit %>
</div>

app/views/tickets/_ticket_fields.html.erb
<% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% @ticket.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<div class="field">
  <%= f.label :description %><br>
  <%= f.text_field :description %>
</div>
<div class="field">
  <%= f.input :ticket_date, as: :date_time_picker %>
</div>
<div class="field">
  <%= f.label :quantity %><br>
  <%= f.number_field :quantity %>
</div>
<div class="field">
  <%= f.label :op_type %><br>
  <%= f.input_field :op_type, include_blank: false %>
</div>

app/views/tickets/_ticket_inline_fields.html.erb
<%= f.inline_div do %>
    <%= f.inline_row_data(class: 'my-row-data') do %>
        <%= f.inline_input :description, as: :string, input_html: {class: 'styled'}, wrapper_html: {class: 'col-xs-7'} %>
        <%= f.inline_input :ticket_date, as: :date_time_picker, input_html: {class: 'styled'}, wrapper_html: {class: 'col-xs-2'} %>
        <%= f.inline_input :quantity, input_html: {style: 'width:60px'}, wrapper_html: {class: 'col-xs-1'} %>
        <%= f.inline_input :op_type, input_html: {class: 'styled'}, wrapper_html: {class: 'col-xs-1'}, include_blank: false %>

        <%= f.inline_row_actions do %>
            <%= f.inline_button_remove 'Remove' %>
            <%= f.inline_button_edit 'Edit' %>
        <% end %>
    <% end %>
<% end %>

app/views/tickets/edit.html.erb
<h1><%= t('.title', customer: @ticket.customer.name) %></h1>

<%= simple_form_for(@ticket) do |f| %>
	<%= render 'form', f: f, customer: @ticket.customer %>
<% end %>

<%= link_to t('back'), customer_tickets_path(@ticket.customer) %>

app/views/tickets/index.html.erb
<h1><%= t('.title', {customer:@customer.name}) %></h1>

<table class="grid">
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.ticket.description') %></th>
      <th><%= t('activerecord.attributes.ticket.ticket_date') %></th>
      <th><%= t('activerecord.attributes.ticket.balance') %></th>
      <th class="not-print"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.description %></td>
        <td class="date"><%= l ticket.ticket_date %></td>
        <td class="number"><%= ticket.balance %></td>
        <td class="links"><%= link_to t('edit').titleize, edit_ticket_path(ticket) %>&nbsp;<%= link_to t('destroy').titleize, ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<b><%= t('activerecord.attributes.customer.tickets_balance') %>: <%= @customer.tickets_balance %></b>
<br>
<br>
<div class="not-print">
    <%= link_to tt('.new'), new_customer_ticket_path(@customer), class: 'btn' %>
    <br>
    <br>
    <%= link_to tt('back'), customers_path %>
</div>

app/views/tickets/new.html.erb
<h1><%= t('.title', customer: @customer.name) %></h1>

<%= simple_form_for([@customer, @ticket]) do |f| %>
	<%= render 'form', f: f, customer: @customer %>
<% end %>

<%= link_to t('back'), customer_tickets_path(@customer) %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @ticket.description %>
</p>

<p>
  <strong>Ticket date:</strong>
  <%= @ticket.ticket_date %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @ticket.quantity %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @ticket.customer_id %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', customer_tickets_path(@ticket.customer) %>